[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pandas", "python3Packages.numpy", "python3Packages.mecab-python3", "python3Packages.unidic-lite", "mecab", "python3Packages.pip"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "PYTHONPATH=/nix/store/*-python3-*/lib/python3.*/site-packages:$PYTHONPATH npm start"

